cltbanco:
  target: dev # target padrao
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('PASS') }}"
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: silver
      threads: 4
    prod:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('PASS') }}"
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: gold
      threads: 4
  